### ISSUE TITLE
Need to figure the INF equiv of %APPDATALOCAL%

### ISSUE THREAD

**Issue by shanselman** [shanselman/WindowsTerminalHere#1]
I need to figure the INF equiv of %APPDATALOCAL% because this

`HKCR,Directory\Shell\WindowsTerminalHere\command,,,""c:\users\scott\appdata\local\Microsoft\WindowsApps\wt.exe -d " ""%1"""`

needs to be something like this

`HKCR,Directory\Shell\WindowsTerminalHere\command,,,""PATHTOAPPDATALOCAL\Microsoft\WindowsApps\wt.exe -d " ""%1"""
`
and so far neither %APPDATALOCAL% nor $APPDATALOCAL$ work

**Comment by Novakov** [comment]
To expand environment variables value must have type `REG_EXPAND_SZ`. In INF files values are of `REG_SZ` type by default. To use  `REG_EXPAND_SZ` it is necessary to add `0x00020000` to flags.

Snippet below adds `REG_EXPAND_SZ` value:
```
[version]
signature="$CHICAGO$"

[DefaultInstall]
AddReg    = ABC.Reg

[ABC.Reg]
HKCU,test,DisplayName,0x00020000,"%ENV_VARIABLE%" 
```

Source: https://docs.microsoft.com/en-us/windows-hardware/drivers/install/inf-addreg-directive

**Comment by japj** [comment]
Not sure what kind of inf file this is, but https://docs.microsoft.com/en-us/windows-hardware/drivers/install/general-syntax-rules-for-inf-files implies that escaping % with % might do the trick?

**Comment by riverar** [comment]
Also: `%APPDATALOCAL%` is not valid. I think you mean `%LOCALAPPDATA%`.

**Comment by shanselman** [comment]
Yes, thanks! @riverar that's my fat fingers! It's three things
* double escape %%
* REG_EXPAND_SX
* use the correct ENV var ;)

Got it! https://github.com/shanselman/WindowsTerminalHere/commit/248629c8cb52ce4c649600ff9717f98277553b15#diff-b218f023c92ea87bfefd7277d503b3c9
