### ISSUE TITLE
Is it support Windows 7 64 bit?

### ISSUE THREAD

**Issue by iam-gopi** [shanselman/WindowsTerminalHere#11]
I have downloaded the inf file and installed it as per the comments. but unfortunately, I couldn't get it to work. Can you help me, please?

I know the WindowsApp folder is not available in my C drive so that's ok to not load the icon. but why terminal is not opening?

**Comment by jawn** [comment]
FYI, support for Windows 7 ended on January 14, 2020. If you are still using Windows 7, your PC may become more vulnerable to security risks.

Source: https://www.microsoft.com/en-us/microsoft-365/windows/end-of-windows-7-support

**Comment by iam-gopi** [comment]
oops thanks for the info

**Comment by chungweileong94** [comment]
You need to [install Windows Terminal](https://github.com/microsoft/terminal#installing-and-running-windows-terminal) separately.
But unfortunately, it requires Windows 10 1903 (build 18362) or later

**Comment by iam-gopi** [comment]
oh thanks @chungweileong94 for the answer. Anyway, I need to upgrade to Windows 10 it seems. let me do that first

**Comment by jawn** [comment]
Hi @itguyofficial , can you close the issue if it's handled for you?

**Comment by iam-gopi** [comment]
oh yea sure will close it
