### ISSUE TITLE
Allow it to open terminal in a directory 

### ISSUE THREAD

**Issue by musm** [shanselman/WindowsTerminalHere#2]
Could we also add the option to add "Open Terminal here" when right-clicking **in** a directory.

**Comment by shanselman** [comment]
What do you mean? Isn't this, that?

**Comment by musm** [comment]
It works if I right click on a selected folder. I would also like it to work if I right-click in the folder itself.

**Comment by musm** [comment]
![t2](https://user-images.githubusercontent.com/4319522/74479842-e3537f00-4e7d-11ea-94f8-2d313218ea50.gif)

**Comment by musm** [comment]
In the GIF when I right click an empty area of the folder, "open terminal here" is not present.  However "Open with Code"  is present. I'd like to also have "open terminal here" in that context menu as well.

**Comment by shanselman** [comment]
OK, let me look into it.
--
Scott Hanselman
@shanselman <http://twitter.com/shanselman> - Podcast:
https://hanselminutes.com/shows
