### ISSUE TITLE
Add windows terminal icon to context menu entries

### ISSUE THREAD

**Issue by etheralm** [shanselman/WindowsTerminalHere#5]
Hi,

it would be nice to have the windows terminal icon next to the context menu entries. 

Currently I added them by hand by putting the windows terminal icon in `%LOCALAPPDATA%\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState` 
(the location of the profiles.json file)

Then I added a new string value named `Icon` in: 
`Computer\HKEY_CLASSES_ROOT\Directory\Background\shell\WindowsTerminalHere`
`Computer\HKEY_CLASSES_ROOT\Directory\shell\WindowsTerminalHere` and
`Computer\HKEY_CLASSES_ROOT\Drive\shell\WindowsTerminalHere`
with the value:
`%LOCALAPPDATA%\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\terminal.ico`

I can write a quick script to automate the process and submit a PR, but it would complicate the installation a bit.

**Comment by chungweileong94** [comment]
It's cool, but personally I won't recommend to include this. as this repo only serves as a temporary solution, it might be a mess when performing the uninstall.

**Comment by etheralm** [comment]
Yeah that's why I didn't bother writing the script in the first place, I opened this ticket more to put the info somewhere on how to add an icon if someone is interested.
